//! ABI-exact public method tables and active-profile global configuration root.

pub const Mutex = opaque {};
pub const PageCache = opaque {};
pub const PageCachePage = opaque {};

pub const MemMethods = extern struct {
    xMalloc: ?*const fn (c_int) callconv(.c) ?*anyopaque,
    xFree: ?*const fn (?*anyopaque) callconv(.c) void,
    xRealloc: ?*const fn (?*anyopaque, c_int) callconv(.c) ?*anyopaque,
    xSize: ?*const fn (?*anyopaque) callconv(.c) c_int,
    xRoundup: ?*const fn (c_int) callconv(.c) c_int,
    xInit: ?*const fn (?*anyopaque) callconv(.c) c_int,
    xShutdown: ?*const fn (?*anyopaque) callconv(.c) void,
    pAppData: ?*anyopaque,
};

pub const MutexMethods = extern struct {
    xMutexInit: ?*const fn () callconv(.c) c_int,
    xMutexEnd: ?*const fn () callconv(.c) c_int,
    xMutexAlloc: ?*const fn (c_int) callconv(.c) ?*anyopaque,
    xMutexFree: ?*const fn (?*anyopaque) callconv(.c) void,
    xMutexEnter: ?*const fn (?*anyopaque) callconv(.c) void,
    xMutexTry: ?*const fn (?*anyopaque) callconv(.c) c_int,
    xMutexLeave: ?*const fn (?*anyopaque) callconv(.c) void,
    xMutexHeld: ?*const fn (?*anyopaque) callconv(.c) c_int,
    xMutexNotheld: ?*const fn (?*anyopaque) callconv(.c) c_int,
};

pub const PcacheMethods2 = extern struct {
    iVersion: c_int,
    pArg: ?*anyopaque,
    xInit: ?*const fn (?*anyopaque) callconv(.c) c_int,
    xShutdown: ?*const fn (?*anyopaque) callconv(.c) void,
    xCreate: ?*const fn (c_int, c_int, c_int) callconv(.c) ?*PageCache,
    xCachesize: ?*const fn (?*PageCache, c_int) callconv(.c) void,
    xPagecount: ?*const fn (?*PageCache) callconv(.c) c_int,
    xFetch: ?*const fn (?*PageCache, c_uint, c_int) callconv(.c) ?*PageCachePage,
    xUnpin: ?*const fn (?*PageCache, ?*PageCachePage, c_int) callconv(.c) void,
    xRekey: ?*const fn (?*PageCache, ?*PageCachePage, c_uint, c_uint) callconv(.c) void,
    xTruncate: ?*const fn (?*PageCache, c_uint) callconv(.c) void,
    xDestroy: ?*const fn (?*PageCache) callconv(.c) void,
    xShrink: ?*const fn (?*PageCache) callconv(.c) void,
};

pub const Sqlite3Config = extern struct {
    bMemstat: c_int,
    bCoreMutex: u8,
    bFullMutex: u8,
    bOpenUri: u8,
    bUseCis: u8,
    bSmallMalloc: u8,
    bExtraSchemaChecks: u8,
    mxStrlen: c_int,
    neverCorrupt: c_int,
    szLookaside: c_int,
    nLookaside: c_int,
    nStmtSpill: c_int,
    m: MemMethods,
    mutex: MutexMethods,
    pcache2: PcacheMethods2,
    pHeap: ?*anyopaque,
    nHeap: c_int,
    mnReq: c_int,
    mxReq: c_int,
    szMmap: i64,
    mxMmap: i64,
    pPage: ?*anyopaque,
    szPage: c_int,
    nPage: c_int,
    mxParserStack: c_int,
    sharedCacheEnabled: c_int,
    szPma: u32,
    isInit: c_int,
    inProgress: c_int,
    isMutexInit: c_int,
    isMallocInit: c_int,
    isPCacheInit: c_int,
    nRefInitMutex: c_int,
    pInitMutex: ?*Mutex,
    xLog: ?*const fn (?*anyopaque, c_int, ?[*:0]const u8) callconv(.c) void,
    pLogArg: ?*anyopaque,
    mxMemdbSize: i64,
    xTestCallback: ?*const fn (c_int) callconv(.c) c_int,
    bLocaltimeFault: c_int,
    xAltLocaltime: ?*const fn (?*const anyopaque, ?*anyopaque) callconv(.c) c_int,
    iOnceResetThreshold: c_int,
    szSorterRef: u32,
    iPrngSeed: c_uint,
};

pub const config_default = struct {
    pub const allow_covering_index_scan: u8 = 1;
    pub const lookaside = [2]c_int{ 1200, 40 };
    pub const memory_database_max_size: i64 = 1_073_741_824;
    pub const sorter_pma_size: u32 = 250;
    pub const statement_journal_spill: c_int = 64 * 1024;
};

pub const initial_config = Sqlite3Config{
    .bMemstat = 1,
    .bCoreMutex = 1,
    .bFullMutex = 1,
    .bOpenUri = 0,
    .bUseCis = config_default.allow_covering_index_scan,
    .bSmallMalloc = 0,
    .bExtraSchemaChecks = 1,
    .mxStrlen = 0x7fff_fffe,
    .neverCorrupt = 0,
    .szLookaside = config_default.lookaside[0],
    .nLookaside = config_default.lookaside[1],
    .nStmtSpill = config_default.statement_journal_spill,
    .m = .{
        .xMalloc = null,
        .xFree = null,
        .xRealloc = null,
        .xSize = null,
        .xRoundup = null,
        .xInit = null,
        .xShutdown = null,
        .pAppData = null,
    },
    .mutex = .{
        .xMutexInit = null,
        .xMutexEnd = null,
        .xMutexAlloc = null,
        .xMutexFree = null,
        .xMutexEnter = null,
        .xMutexTry = null,
        .xMutexLeave = null,
        .xMutexHeld = null,
        .xMutexNotheld = null,
    },
    .pcache2 = .{
        .iVersion = 0,
        .pArg = null,
        .xInit = null,
        .xShutdown = null,
        .xCreate = null,
        .xCachesize = null,
        .xPagecount = null,
        .xFetch = null,
        .xUnpin = null,
        .xRekey = null,
        .xTruncate = null,
        .xDestroy = null,
        .xShrink = null,
    },
    .pHeap = null,
    .nHeap = 0,
    .mnReq = 0,
    .mxReq = 0,
    .szMmap = 0,
    .mxMmap = 0x7fff_0000,
    .pPage = null,
    .szPage = 0,
    .nPage = 20,
    .mxParserStack = 0,
    .sharedCacheEnabled = 0,
    .szPma = config_default.sorter_pma_size,
    .isInit = 0,
    .inProgress = 0,
    .isMutexInit = 0,
    .isMallocInit = 0,
    .isPCacheInit = 0,
    .nRefInitMutex = 0,
    .pInitMutex = null,
    .xLog = null,
    .pLogArg = null,
    .mxMemdbSize = config_default.memory_database_max_size,
    .xTestCallback = null,
    .bLocaltimeFault = 0,
    .xAltLocaltime = null,
    .iOnceResetThreshold = 0x7fff_fffe,
    .szSorterRef = 0x7fff_ffff,
    .iPrngSeed = 0,
};

pub var global_config = initial_config;
